#!/bin/bash --login

activate()
{
    if [[ $# -ne 1 ]]; then
        echo "need one arg"
        exit 1
    fi
    if [[ -z $BALSAM_DB_ACTIVE ]]; then
        export BALSAM_DB_ACTIVE=1
    else
        echo "Balsam DB $BALSAM_DB_PATH is already active! Use exit to quit."
        exit 1
    fi
    echo "activating $BALSAM_DB_PATH..."

    export BALSAM_DB_PATH=$1
    export BALSAM_DB_ACTIVE=1
    export PS1_OLD=$PS1
    exec /bin/bash --rcfile <(echo 'export PS1="(BalsamDB: $BALSAM_DB_PATH) $PS1"')
}

deactivate()
{
    if [[ -z $BALSAM_DB_ACTIVE ]]; then
        echo "There is no active BalsamDB"
        exit 1
    else
        echo "Use 'exit' to quit the current Balsam subshell"
    fi

}

if [[ $1 =~ ^(activate|deactivate)$ ]]; then
  "$@"
else
  echo "Invalid subcommand $1" >&2
  exit 1
fi
