#!/bin/bash
set -e
SCRIPTPATH="$( cd "$(dirname "$0")" ; pwd -P )"

if [[ $# -ne 1 ]]; then
    echo "Usage: $0 <database-path>"
    exit 1
fi

if [ -d $1 ]; then
    echo "Error: $1 already exists"
    exit 1
fi

pwfile=/tmp/pwfile.$$.$USER
touch $pwfile && chmod 600 $pwfile
$SCRIPTPATH/make-token.py > $pwfile
initdb --auth scram-sha-256 -D $1 --pwfile $pwfile -U postgres
mv $pwfile $1/pwfile
