version: 2

updates:
- package-ecosystem: pip
  directory: /requirements/
  target-branch: main
  schedule:
    interval: weekly
    
- package-ecosystem: pip
  directory: /
  target-branch: main
  schedule:
    interval: weekly


- package-ecosystem: github-actions
  directory: /
  target-branch: main
  schedule:
    interval: monthly

- package-ecosystem: docker
  directory: /
  target-branch: main
  schedule:
    interval: monthly
