version: "3.9"

services:
  gunicorn:
    container_name: gunicorn
    build: .
    image: masalim2/balsam
    restart: always
    ports:
      - 8000:8000
    depends_on:
      postgres:
        condition: service_healthy
      redis:
        condition: service_started
    environment:
      BALSAM_DATABASE_URL: postgresql://postgres:postgres@postgres:5432/balsam
      BALSAM_SERVER_BIND: "0.0.0.0:8000"
      BALSAM_REDIS_PARAMS: '{"host": "redis", "port": "6379"}'
      BALSAM_LOG_LEVEL:
      BALSAM_LOG_DIR:
      BALSAM_NUM_UVICORN_WORKERS:
    volumes:
      - "${BALSAM_LOG_DIR}:/balsam/log"
      - "./balsam:/balsam/balsam:ro"
      - "./tests:/balsam/tests:ro"

  postgres:
    container_name: postgres
    image: postgres
    restart: always
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: balsam
    volumes:
      - "pgdata:/var/lib/postgresql/data"
    command: "-c log_min_duration_sample=2s -c log_statement_sample_rate=0.2"
    logging:
      options:
        max-size: "50m"
        max-file: "5"
      driver: "json-file"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 6

  redis:
    container_name: redis
    image: redis
    restart: always
    ports:
      - 6379:6379

volumes:
  pgdata:
