site_name: Balsam
nav:
  - Home: README.md
  - Development:
      - Understanding Balsam: development/data-model.md
      - Project Layout: development/layout.md
      - Contribution Guide: development/contributing.md
      - Integration Testing: development/testing.md
      - Site Configuration: development/site-config.md
      - The Python REST Client: development/client.md
      - Defining Applications: development/appdef.md
      - Web Client: development/web-client.md
      - Roadmap: development/todo.md
  - Running a Balsam Server: development/deploy.md
  - Tutorials:
    - ALCF-Theta Quickstart: tutorials/theta-quickstart.md
  - License: LICENSE.md


theme:
  name: 'material'
  language: 'en'
  palette:
    primary: 'teal'
    accent: 'amber'
  features:
    - tabs
    - instant
  icon: 
    logo: material/cloud

markdown_extensions:
  - admonition
  - codehilite
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.superfences:
      custom_fences:
          - name: mermaid
            class: mermaid
            format: !!python/name:pymdownx.superfences.fence_div_format

extra_css: 
  - extra.css

extra_javascript: 
  - mermaid.min.js

repo_name: 'balsam-alcf/balsam'
repo_url: 'https://github.com/balsam-alcf/balsam'

extra:
  social:
    - icon: 'fontawesome/brands/github-alt'
      link: 'https://github.com/balsam-alcf'

plugins:
  - search

