site_name: Balsam
nav:
  - Home: README.md
  - Tutorials:
    - ALCF-Theta Quickstart: tutorials/theta-quickstart.md
  - User Guide:
    - Installation: user-guide/installation.md
  - Developer Guide:
      - Developer Installation: development/installation.md
      - Understanding Balsam: development/data-model.md
      - Project Layout: development/layout.md
      - Contribution Guide: development/contributing.md
      - Integration Testing: development/testing.md
      - Site Configuration: development/site-config.md
      - The Python REST Client: development/client.md
      - Defining Applications: development/appdef.md
      - Web Client: development/web-client.md
      - Roadmap: development/todo.md
  - Running a Balsam Server: development/deploy.md
  - License: LICENSE.md


theme:
  name: 'material'
  language: 'en'
  palette:
    primary: 'indigo'
    accent: 'amber'
    scheme: 'preference'
  features:
    - tabs
    - instant
  logo: './img/Argonne_wireframe_white_transparent.png'
  favicon: './img/alcf_favicon.ico'

markdown_extensions:
  - admonition
  - codehilite
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.superfences:
      custom_fences:
          - name: mermaid
            class: mermaid
            format: !!python/name:pymdownx.superfences.fence_div_format

extra_css: 
  - extra.css

extra_javascript: 
  - mermaid.min.js

repo_name: 'argonne-lcf/balsam'
repo_url: 'https://github.com/argonne-lcf/balsam'

extra:
  social:
    - icon: 'fontawesome/brands/github-alt'
      link: 'https://github.com/argonne-lcf/balsam'

plugins:
  - search

