site_name: Balsam
nav:
  - Home: README.md 
  - User Guide:
      - "Getting Started": userguide/getting-started.md
      - "Configuration": userguide/configuration.md
      - "The Database": userguide/db.md
      - "Defining Applications": userguide/app.md
      - "Submitting Jobs": userguide/submit.md
      - "Multi-user Collaboration": userguide/multi-user.md
  - Application Tutorials:
    - "DeepHyper": tutorial/deephyper.md
    - "NWChem: Parameter Sweep": tutorial/nwchem.md
    - "Containerizing Single-node MPI Applications": tutorial/nwcontainer.md
    - "Using Jupyter (Experimental)": tutorial/balsam_monitor.ipynb
  - Frequently Asked Questions: faq/recipes.md
  - License: LICENSE.md


theme:
  name: 'material'
  language: 'en'
  palette:
    primary: 'teal'
    accent: 'amber'
  features:
    - tabs
    - instant
  icon: 
    logo: material/cloud

markdown_extensions:
  - admonition
  - codehilite

extra_css: [extra.css]

repo_name: 'balsam-alcf/balsam'
repo_url: 'https://github.com/balsam-alcf/balsam'

extra:
  social:
    - icon: fontawesome/brands/git-alt
      link: 'https://github.com/balsam-alcf'

plugins:
  - mkdocs-jupyter
  - search
