site_name: Balsam
site_url: https://balsam.readthedocs.io/en/latest/
nav:
  - Home: README.md
  - Tutorials:
    - Getting Started: tutorials/theta-quickstart.md
  - User Guide:
    - Installation: user-guide/installation.md
    - Creating Balsam Sites: user-guide/site-config.md
    - Defining Apps: user-guide/appdef.md
    - The Command Line: user-guide/cli.md
    - Managing Jobs: user-guide/jobs.md
    - The Python API: user-guide/api.md
    - Executing Jobs: user-guide/batchjob.md
    - Workflow Monitoring and Analytics: user-guide/monitoring.md
    - Auto Scaling: user-guide/elastic.md
    - Data Transfers: user-guide/transfer.md
  - Developer Guide:
      - Instructions: development/contributing.md
      - Understanding the Data Model: development/data-model.md
      - Project Layout: development/layout.md
      - Porting to New Sites: development/porting.md
      - Integration Testing: development/testing.md
      - The Python REST Client: development/client.md
  - Admin Guide: development/deploy.md
  - Publications: community/publications.md
  - License: LICENSE.md


theme:
  name: 'material'
  language: 'en'
  palette:
    primary: 'indigo'
    accent: 'amber'
    scheme: 'preference'
  features:
    - navigation.instant
    - navigation.tabs
  logo: './img/balsam_favicon.ico'
  favicon: './img/balsam_favicon.ico'

markdown_extensions:
  - admonition
  - codehilite
  - attr_list
  - toc:
      permalink: true
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.superfences:
      custom_fences:
          - name: mermaid
            class: mermaid
            format: !!python/name:pymdownx.superfences.fence_div_format
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg

extra_css: 
  - extra.css

extra_javascript: 
  - mermaid.min.js

repo_name: 'argonne-lcf/balsam'
repo_url: 'https://github.com/argonne-lcf/balsam'
edit_uri: edit/main/docs/

extra:
  social:
    - icon: 'fontawesome/brands/github-alt'
      link: 'https://github.com/argonne-lcf/balsam'

plugins:
  - search

