#!/usr/bin/env bash
source env/bin/activate
export ARGOBALSAM_INSTALL_PATH=$(pwd)
export PYTHONPATH=$ARGOBALSAM_INSTALL_PATH:$PYTHONPATH
export PATH=$ARGOBALSAM_INSTALL_PATH/balsam/bin:$PATH
export ARGOBALSAM_DATA_PATH=$ARGOBALSAM_INSTALL_PATH/data
export ARGOBALSAM_EXE_PATH=$ARGOBALSAM_INSTALL_PATH/exe
