#!/bin/bash

[[ "$0" = *"balsamactivate"* ]] && echo "Error: Must source this script. Run 'source balsamactivate' instead of 'balsamactivate'" && exit

_py_resolve_path ()
{
    python -c "import os; print(os.path.abspath(\"$1\"))"
}

_py_basename ()
{
    python -c "import os; print(os.path.basename(\"$1\"))"
}

_resolver=$(which readlink -f || _py_resolve_path)
_get_basename=$(which basename || _py_basename)

_setup_env ()
{
    export BALSAM_SITE_PATH=$1

    if [ ! -z "$OLD_PS1" ]
    then
        export PS1=$OLD_PS1
        unset OLD_PS1
    fi
    export OLD_PS1=$PS1
    export PS1="[Balsam: $(_get_basename $1)] $PS1"
    _balsam_completionetup;
}

_balsam_completion() {
    local IFS=$'
'
    COMPREPLY=( $( env COMP_WORDS="${COMP_WORDS[*]}" \
                   COMP_CWORD=$COMP_CWORD \
                   _BALSAM_COMPLETE=complete $1 ) )
    return 0
}

_balsam_completionetup() {
    local COMPLETION_OPTIONS=""
    local BASH_VERSION_ARR=(${BASH_VERSION//./ })
    # Only BASH version 4.4 and later have the nosort option.
    if [ ${BASH_VERSION_ARR[0]} -gt 4 ] || ([ ${BASH_VERSION_ARR[0]} -eq 4 ] && [ ${BASH_VERSION_ARR[1]} -ge 4 ]); then
        COMPLETION_OPTIONS="-o nosort"
    fi

    complete $COMPLETION_OPTIONS -F _balsam_completion balsam
}


site_path=$(_resolver $1)

if [ ! -d $site_path ] || [ ! -f $site_path/settings.py ]
then
    echo "Invalid site path: $site_path"
    return 1
fi

balsam activate service $site_path && _setup_env $site_path
