#!/bin/bash

[[ "$0" = *"balsamactivate"* ]] && echo "Must source this script" && exit

known_list=$(balsam which --list 2> /dev/null)
if [ $? -ne 0 ]
then
    echo "Balsam is not configured properly; please check installation"
    return 1
fi

USAGE="Usage: balsamactivate {db_name}"
USAGE+=$'\nKnown databases:\n'
USAGE+=$known_list
USAGE+=$'\nUse "balsam init" to create a new DB, or provide an existing DB path to balsamactivate'

if [ $# -ne 1 ]
then
    echo "$USAGE"
    return 1
fi

if [ ! -d $1 ]
then
    db_path=$(balsam which --name $1)
    if [ $? -ne 0 ]
    then
        return 1
    fi
else
    if [ ! -f $1/dbwriter_address ]
    then
        echo "No Balsam DB found in dir $1"
        return 1
    fi
    db_path=$1
    temp=$(BALSAM_DB_PATH=$db_path balsam which --list 2> /dev/null)
fi

export BALSAM_DB_PATH=$db_path
if [ ! -z "$OLD_PS1" ]
then
    export PS1=$OLD_PS1
    unset OLD_PS1
fi
export OLD_PS1=$PS1
export PS1="[BalsamDB: $(basename $1)] $PS1"
return 0
