# Default local setup for Mac OS
filter_tags: {}
logging:
    buffer_num_records: 1024
    datefmt: '%d-%b-%Y %H:%M:%S'
    flush_period: 30
    format: '%(asctime)s|%(process)d|%(thread)d|%(levelname)8s|%(name)s:%(lineno)s]
        %(message)s'
    level: DEBUG
mpi_launcher: balsam.platform.mpirun.theta.ThetaAprun
processing:
    num_workers: 1
    prefetch_depth: 1000
resource_manager: balsam.platform.nodespec.default.DefaultNode
scheduler:
    allowed_projects:
    - local
    allowed_queues:
        local:
            max_nodes: 1
            max_queued_jobs: 1000
            max_walltime: 60
    job_template_path: job-template.sh.tmpl
    optional_batch_job_params:
        shout: 'no'
    scheduler_class: balsam.platform.scheduler.LocalProcessScheduler
    sync_period: 10
queue_maintainer: null
site_id: -1
transfers:
    globus_endpoint_id: null
    max_concurrent_transfers: 5
    transfer_locations:
        theta_dtn: globus://08925f04-569f-11e7-bef8-22000b9a448b
