# Default setup for Theta KNL cluster @ ALCF
logging:
    buffer_num_records: 1024
    datefmt: '%d-%b-%Y %H:%M:%S'
    flush_period: 30
    format: '%(asctime)s|%(process)d|%(thread)d|%(levelname)8s|%(name)s:%(lineno)s]
        %(message)s'
    level: DEBUG
mpi_launcher: balsam.platform.mpirun.theta.ThetaAprun
processing:
    num_workers: 5
    prefetch_depth: 1000
resource_manager: balsam.platform.nodespec.default.DefaultNode
scheduler:
    allowed_projects:
    - datascience
    allowed_queues:
        debug-cache-quad:
            max_nodes: 8
            max_queued_jobs: 1
            max_walltime: 60
        debug-flat-quad:
            max_nodes: 8
            max_queued_jobs: 1
            max_walltime: 60
        default:
            max_nodes: 4010
            max_queued_jobs: 20
            max_walltime: 1440
    job_template_path: job-template.sh
    optional_batch_job_params:
        singularity_prime_cache: 'no'
    scheduler_class: balsam.platform.scheduler.cobalt_sched.CobaltScheduler
    sync_period: 60
site_id: -1
transfers:
    globus_endpoint_id: null
    max_concurrent_transfers: 5
    transfer_locations:
        theta_dtn: globus://08925f04-569f-11e7-bef8-22000b9a448b
