title: "Aurora (ALCF)"

compute_node: balsam.platform.compute_node.AuroraNode
mpi_app_launcher: balsam.platform.app_run.AuroraRun
local_app_launcher: balsam.platform.app_run.LocalAppRun
mpirun_allows_node_packing: true

serial_mode_startup_params: 
    cpu_affinity: none

scheduler_class: balsam.platform.scheduler.PBSScheduler
allowed_queues:
    workq:
        max_nodes: 128
        max_queued_jobs: 1
        max_walltime: 240

allowed_projects:
- Aurora_deployment

optional_batch_job_params: {}
