title: "Aurora (ALCF)"

compute_node: balsam.platform.compute_node.AuroraNode
mpi_app_launcher: balsam.platform.app_run.AuroraRun
local_app_launcher: balsam.platform.app_run.LocalAppRun
mpirun_allows_node_packing: true

serial_mode_startup_params: 
    cpu_affinity: none

scheduler_class: balsam.platform.scheduler.PBSScheduler
allowed_queues:
    debug:
        max_nodes: 2
        max_queued_jobs: 1
        max_walltime: 60
    debug-scaling:
        max_nodes: 31
        max_queued_jobs: 1
        max_walltime: 60
    prod:
        max_nodes: 2048
        max_queued_jobs: 100
        max_walltime: 1080

allowed_projects:
- Aurora_deployment

optional_batch_job_params: {}
